#!/usr/bin/env python3
"""Write docs/data.js from the scenario and the recovery study."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
DOCS = ROOT / "docs"


def main() -> int:
    scen = json.loads((DATA / "scenario.json").read_text())
    rec = json.loads((DATA / "recovery.json").read_text())
    payload = dict(scen)
    payload["closure_day"] = rec["closure_day"]
    payload["recovery"] = rec
    DOCS.mkdir(parents=True, exist_ok=True)
    out = "/* generated by study/build_page_data.py, do not edit */\nconst D = " + \
        json.dumps(payload, separators=(",", ":")) + ";\n"
    (DOCS / "data.js").write_text(out)
    print(f"wrote docs/data.js ({len(out) // 1024} KB), "
          f"{len(payload['edges'])} segments, {len(rec['sweep'])} recovery points")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
